### PR TITLE
Got familiar with Basic Linux Commands for Directories and Files

### PR DESCRIPTION
**Pull request by Vaibhav-Patel19**

### CODE REVIEW

**Review by saiyam1814 — CHANGES_REQUESTED** [review]
Please create separate folders for each day !

**Comment by kranurag7** [comment]
@Vaibhav-Patel19 Please create a folder for each day so that if you look back at your learning journey it will make more sense to you. You can also create the folder topic wise if you want.

**Comment by saiyam1814** [comment]
@Vaibhav-Patel19 can you create separate folders for each day, @kranurag7 can help you out if you are stuck!

**Comment by saiyam1814** [comment]
@Vaibhav-Patel19 can you do the requested changes please?

**Comment by kranurag7** [comment]
@Vaibhav-Patel19 Do ask your questions here if you're getting stuck somewhere?

**Comment by saiyam1814** [comment]
Closing this due to inactivity, feel free to open a new PR with progress.

**Pull request closed without merging**
