### PR TITLE
day 2 progress

### PR DESCRIPTION
**Pull request by nayabatir1**
Is there any free course for linux on edx. [Link](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbE5QMkFyVWhtQWp1UDNxRGtjdHN4UnhpbkxOUXxBQ3Jtc0ttRnozNHZaSTlZaXkxeWVGVXF4bVBBbGE1bVA2MnJVWHR5V3h4Sm8zdC04YzU3b3ZWWElaMzU4ajl1M1plbVluZy1yMUFac2xaMS10NDd4MjFLcGxMMUVSbXVoQVBRaWRzRExXOFBmME50NDctY2lUNA&q=https%3A%2F%2Fwww.edx.org%2Fcourse%2Fintroduction-to-linux) you mentioned is paid one, and has 7 day trail period with limited access.

### CODE REVIEW

**Comment by saiyam1814** [comment]
@nayabatir1 the course is completely free! 
image
Just enroll without certificate and view course

**Comment by nayabatir1** [comment]
My bad I got confused when I saw 7 days left now it is 6 days
image

**Comment by nayabatir1** [comment]
> @nayabatir1 the course is completely free! image Just enroll without certificate and view course

My bad I got confused when I saw 7 days left now it is 6 days
image

**Comment by saiyam1814** [comment]
I do not know why are you choosing the certificate, you enrol to the course you get 2 options!! 
image

And access the course 

image

You can choose the free one but obviously if you want certificate then you need to pay but the course and its content is free!

**Comment by nayabatir1** [comment]
image

As you can see I've enrolled for free one. I'm not opting for certification that's why I'm getting option to upgrade. Sorry for bothering you.😞

**Review by saiyam1814 — CHANGES_REQUESTED** [review]
LGTM

**Pull request merged**
