### PR TITLE
added folder with my name

### PR DESCRIPTION
**Pull request by orrgato**

### CODE REVIEW

**Comment by kranurag7** [comment]
@orrgato  Glad to have you here 👋. Please create a folder for each day and update your learning along with notes. If you get stuck or need any help feel free to ping me.

**Comment by orrgato** [comment]
Hey ,
I am new to github, Today I was trying to update my Readme file today and
somehow things got messed up.
I tried to correct things by watching youtube videos and it just kept
getting worse.
and I naively deleted the 'main' branch and deleted past commits.
I was hoping to start from the beginning by cloning the whole project.
Is there any possibility to do so ?

**Comment by orrgato** [comment]
I am having this error when pushing changes to my folder . 

remote: Permission to saiyam1814/DevOpsRoadmap2022.git denied to orrgato.
fatal: unable to access 'https://github.com/saiyam1814/DevOpsRoadmap2022.git/': The requested URL returned error: 403

**Comment by kranurag7** [comment]
@orrgato Try pushing your code directly to your remote repository i.e. the repo your forked and then create a pull request to the upstream repo which is the original repository.

**Comment by orrgato** [comment]
I was trying to make a pull request directly to the original repository, 
I mixed up pull and push request. 

You are a saver , Thank you and sorry for wasting your time over my silly mistakes.

**Comment by kranurag7** [comment]
@orrgato No need for sorry. We all are learning here. Ping me back if you feel any problem. Everything on git is erasable so don't worry about making mistakes.

**Pull request merged**
