### PR TITLE
Progress till 25-01-22

### PR DESCRIPTION
**Pull request by sadab-halim**
@kranurag7 Please check, I have created a new PR

### CODE REVIEW

**Comment by kranurag7** [comment]
@sadab-halim this branch is still having conflicts. You need to do delete these two files. I am attaching a screenshot. 
conflict

**Comment by sadab-halim** [comment]
Yes, I checked but their is nothing such files in my repo. I had already deleted those files 3 days ago. I can't understand where is the problem and how to resolve.

image
image

**Comment by kranurag7** [comment]
@saiyam1814 Please have a look at this issue. I do not have the access to resolve conflicts. I need your help here.

**Comment by saiyam1814** [comment]
can you delete these files and take from the repo 
Abinash-Pradhan/README.md
Anubhav-Vardhan/README.md
For your Readme I can resolve the conflict but conflict is with a couple other REadme as well

**Comment by sadab-halim** [comment]
> Yes, I checked but their is nothing such files in my repo. I had already deleted those files 3 days ago. I can't understand where is the problem and how to resolve.
> 
> image image

No, i am not able to delete it. I have also run the commands in my system to ddelet, but their were no such files found.

And as you can see in the ss itself, i had already deleted the files nd the delete button is disabled.

**Comment by saiyam1814** [comment]
can you add the exact same files in your repo ? you deleted those from your repo but its there in the main repo so just create those files and commit and let's see

**Comment by sadab-halim** [comment]
Okay

**Comment by sadab-halim** [comment]
Please check, I have added the files.

**Comment by sadab-halim** [comment]
Thank you @saiyam1814 and @kranurag7

**Pull request merged**
