### PR TITLE
Mayank

### PR DESCRIPTION
**Pull request by mayankkuamr001**
- made is folder
- made his README.md

### CODE REVIEW

**Comment by kranurag7** [comment]
@mayankkuamr001 Thank you for creating your PR. Can you please create seperate directory either by topic or by day? Please have a look at other repositories.

**Comment by saiyam1814** [comment]
@mayankkuamr001 do you need any clarifications on the above-mentioned comment by @kranurag7 ?

**Comment by mayankkuamr001** [comment]
Thanks for asking @saiyam1814. @kranurag7 explanation is clear and I will make the changes asap. Today's my 14th day will upload the journey soon. I am documenting my journey on Twitter but couldn't do that on GitHub due to GHW. Extremely sorry for that.

**Comment by mayankkuamr001** [comment]
- Created a new folder
- deleted the old one
- updated my learning till date

**Pull request merged**
