### PR TITLE
devops-roadmap

### PR DESCRIPTION
**Pull request by kranurag7**
Updated all the links of the syllabus here.

### CODE REVIEW

**Comment by kranurag7** [comment]
@nayabatir1 and @saiyam1814 please have a look at this. Any suggestions here?

**Comment by kranurag7** [comment]
Also I have included @kunal-kushwaha YAML course in the YAML section. In future, we will update all the resources here.

**Comment by nayabatir1** [comment]
> @nayabatir1 and @saiyam1814 please have a look at this. Any suggestions here?

Can we add time frame just to keep a check at our pace.

It will help each individual to point out that if I have to increase my pace or not if I want to cover entire thing on time.

I understand every body has a different pace of learning.

**Comment by saiyam1814** [comment]
Great looks good to me @kranurag7 can you also ask people to have this in the Readme and then mark in how many days they completed, and notes in each day folder?

**Comment by saiyam1814** [comment]
@kranurag7 can we also ask people to join Discord saiyampathak.com/discord ? we can create the devopsroadmap channel and then I can add you as the moderator of that. Let me know what you think

**Comment by kranurag7** [comment]
@saiyam1814  I'm perfectly fine with that. Discord would be a great Idea. I will convey both the information in the next PR they create. May be some meet/ discord hangouts will be great with the learning members.

**Comment by saiyam1814** [comment]
yes we can do that ocassionally, Can you send me a message on discord so that I can add you as a contributor and we can increase the interactions! 
Let's make it big and we even want more contributors to join so that people can learn. I am thinking of adding mini projects and assignments for future .

**Review by saiyam1814 — CHANGES_REQUESTED** [review]
can we add a link to this or mention this in the main Readme somewhere ?

**Comment by kranurag7** [comment]
We can add a link to main readme file. Apart from that I'm also creating a `CONTRIBUTING.md` file and we can mention there too.

**Comment by kranurag7** [comment]
@saiyam1814 Should we merge this into the main repo. This pull request contains two changes `syllabus.md` and `CONTRIBUTING.md`

**Comment by saiyam1814** [comment]
LGTM

**Pull request merged**
