### PR TITLE
Learning DevOps

### PR DESCRIPTION
**Pull request by Darshnadas**

### CODE REVIEW

**Review by saiyam1814 — APPROVED** [review]
Thanks for restructuring!

**Comment by saiyam1814** [comment]
This PR has a conflict, please check

**Comment by kranurag7** [comment]
@Darshnadas You are committing 3 commits to the same pull request. Try making the commit one by one. Use `git reset` to reset the changes. Make a new pull request for each day. You can also use branching for each day and then create a PR from each branch.

**Comment by saiyam1814** [comment]
@Darshnadas can you fix it ?

**Comment by Darshnadas** [comment]
@kranurag7 Understood now, thank you for explaining

**Comment by Darshnadas** [comment]
@saiyam1814 Raised this PR from map branch already that's why not removing it, from next time will create different branch everyday and raise a PR

**Comment by kranurag7** [comment]
@Darshnadas Always glad to help. Now the PR looks much better. Thank you for Restructuring.

**Comment by saiyam1814** [comment]
LGTM

**Pull request merged**
