### PR TITLE
25-01-22 Progress

### PR DESCRIPTION
**Pull request by sadab-halim**
I have made the folders day wise from scratch and I have also added my notes along with my learnings.
Some notes are yet to be added, I will be updating the files soon.

### CODE REVIEW

**Comment by kranurag7** [comment]
@sadab-halim This branch is having conflicts. Please try to rectify that. If you face any problem ping me back.

**Comment by sadab-halim** [comment]
Yes, can you please help me how to resolve the conflicts. I tried, but it didn't work.

**Comment by kranurag7** [comment]
@sadab-halim You need to remove Abinash-Pradhan/README.md, 
Anubhav-Vardhan/README.md these two files from your local system and then push again. For removing use 
`git rm Abinash-Pradhan/README.md`
`git rm Anubhav-Vardhan/README.md`

**Comment by sadab-halim** [comment]
I had already deleted those files few days ago, I have also run the commands, but no such file was found.
I am attaching the ss for your reference.
Please look into it.
image

**Comment by sadab-halim** [comment]
These three files are also deleted.
image

**Comment by kranurag7** [comment]
@sadab-halim You have closed this PR as of now. I will request you to create a new PR this time. In the above case I think you have deleted the files in your local repo only. I have cloned your repo and found those two files. Anyways, Please create a new PR again. Ping me back if you need help.

**Comment by sadab-halim** [comment]
Yes, I closed this PR because I was thinking to create a new one.

**Comment by kranurag7** [comment]
Go Ahead @sadab-halim

**Pull request closed without merging**
