### PR TITLE
day 27 progess

### PR DESCRIPTION
**Pull request by nayabatir1**

### CODE REVIEW

**Comment by kranurag7** [comment]
Nice @nayabatir1 If you will insert some images then it will look great.

**Comment by nayabatir1** [comment]
> Nice @nayabatir1 If you will insert some images then it will look great. 

Do .md file allow to directly insert images. Hmm....🤔

**Comment by kranurag7** [comment]
Yes you can insert the image directly. 
`image-name` will add the image to your `.md` file. Ping me back if you get stuck.

**Comment by nayabatir1** [comment]
> Yes you can insert the image directly. 
> `image-name` will add the image to your `.md` file. Ping me back if you get stuck. 

What I meant was I can add with link but if I take screenshot I'll not be able to add.
I have to host to a server and all which is very lengthy.

**Comment by kranurag7** [comment]
No what you can do is create a seperate folder that will contain only images something like `assets` or `code-images`. Store all your images there and give a link to your file path. Look at my directory.

**Pull request merged**
