### PR TITLE
Add my Day-1 Day-2

### PR DESCRIPTION
**Pull request by Shivansh-yadav13**
### Day 1 & Day 2 Added 👾

### CODE REVIEW

**Review by saiyam1814 — CHANGES_REQUESTED** [review]
Please create separate folders for each day , check the examples in the main Readme

**Comment by saiyam1814** [comment]
@Shivansh-yadav13 can you create separate folders for each day ?

**Comment by Shivansh-yadav13** [comment]
> @Shivansh-yadav13 can you create separate folders for each day ?

Done, sorry for the late reply.

**Comment by kranurag7** [comment]
Nice !! @Shivansh-yadav13 Maintain the streak

**Pull request merged**
