### PR TITLE
Bushra Nazish updated Readme file

### PR DESCRIPTION
**Pull request by BushraNazish**

### CODE REVIEW

**Comment by kranurag7** [comment]
@BushraNazish Please create a separate directory for each day or separate your directory topic wise. You can have a look at other repositories.

**Comment by BushraNazish** [comment]
Yeah, I will do it.

**Comment by saiyam1814** [comment]
@BushraNazish were you able to do it or do you need any help ?

**Comment by BushraNazish** [comment]
No, I didn't attempt. I will do it now and ask for help if needed.
Thanks for asking @saiyam1814

**Pull request merged**
