### PR TITLE
Day 17 Progress

### PR DESCRIPTION
**Pull request by sadab-halim**

### CODE REVIEW

**Review by saiyam1814 — CHANGES_REQUESTED** [review]
I would still say to have a look at the examples from the repository readme and make the changes accordingly .

**Comment by sadabhalim7** [comment]
Okay sure, i will make the changes accordingly.

**Comment by saiyam1814** [comment]
Too many PR's , kindly create a single PR to date!

**Comment by sadab-halim** [comment]
Okay, sorry for the inconvenience.

**Pull request closed without merging**
