### PR TITLE
Rajendra Ladkat added Readme file

### PR DESCRIPTION
**Pull request by Rajendraladkat1919**

### CODE REVIEW

**Comment by kranurag7** [comment]
@Rajendraladkat1919 It will be great if you can create day wise or chapter wise folders. It will be good for you when will you look back at your learnings.

**Comment by Rajendraladkat1919** [comment]
@kranurag7  Please review this PR. Please let me know if there is any change.

**Comment by kranurag7** [comment]
@Rajendraladkat1919 Please try to make some changes in the `pipelinetypes.md` Make some differentiations. Separate the codeblocks from the normal text. That will look good.

**Comment by Rajendraladkat1919** [comment]
@kranurag7  Please review now and let me know if I need to make any change in the PR.

**Comment by kranurag7** [comment]
@Rajendraladkat1919 Don't include the paragraphs in code blocks. You will have to scroll horizontally to read it later.

**Comment by kranurag7** [comment]
@Rajendraladkat1919 closing this PR because of inactivity. Feel free to Raise the PR anytime.

**Pull request closed without merging**
